# Import library

In [1]:
# pip install metapy-toolbox or pip install --upgrade metapy-toolbox
from metapy_toolbox import simulated_annealing_01
from my_example import my_obj_function

# Setup

In [2]:
# Algorithm setup
setup = {   
            'number of iterations': 100,
            'number of population': 2,
            'number of dimensions': 2,
            'x pop lower limit': [-5, -5],
            'x pop upper limit': [5, 5],
            'none variable': None,
            'objective function': my_obj_function,
            'algorithm parameters': {
                                        'mutation': {
                                                     'cov (%)': 20,
                                                     'pdf': 'gaussian'
                                                    },
                                        'temp. control': {
                                                          'temperature t_0': 'auto',
                                                          'temperature update': 'geometric',
                                                          'alpha': 0.9
                                                         }
                                    },
        }

# Initial guess
init_pop = [[-0.74, 1.25],
            [3.58, -3.33]]
"""
or # random guess
from metapy_toolbox import initial_population_01
init_pop = initial_population_01(setup['number of population'],
                                setup['number of dimensions'],
                                setup['x pop lower limit'],
                                setup['x pop upper limit'])
"""

seed = None

# Call function

In [3]:
settings = [setup, init_pop, seed]
df_all_results, df_resume, time_cost, report = simulated_annealing_01(settings)

Progress:   0%|          | 0/100 [00:00<?, ?it/s]

Progress: 100%|██████████| 100/100 [00:00<00:00, 651.08it/s]

# Output details

In [4]:
df_all_results

          X_0       X_1         OF       FIT  ITERATION
0   -0.740000  1.250000   2.110100  0.321533          0
1    3.580000 -3.330000  23.905300  0.040152          0
2   -0.819300  1.163797   2.025678  0.330504          1
3    2.941077 -2.945731  17.327267  0.054564          1
4   -0.873360  0.974951   1.713286  0.368557          2
..        ...       ...        ...       ...        ...
197  0.040807 -0.042593   0.003479  0.996533         98
198 -0.003787  0.027548   0.000773  0.999227         99
199  0.037859 -0.021532   0.001897  0.998107         99
200 -0.004103  0.025362   0.000660  0.999340        100
201  0.033774 -0.018988   0.001501  0.998501        100

[202 rows x 5 columns]

In [5]:
df_resume.tail(20)

,X_0_BEST,X_1_BEST,OF BEST,FIT BET,ID BEST,X_0_WORST,X_1_WORST,OF WORST,FIT WORST,ID WORST,OF AVG,FIT AVG,ITERATION,neof
81,-0.041269,0.038214,0.003163,0.996847,0,0.069422,-0.070128,0.009737,0.990357,1,0.006450,0.993602,81,164
82,-0.051526,0.038847,0.004164,0.995853,0,0.085447,-0.057361,0.010591,0.989520,1,0.007378,0.992686,82,166
83,-0.041460,0.040026,0.003321,0.996690,0,0.072845,-0.073304,0.010680,0.989433,1,0.007000,0.993061,83,168
84,-0.036615,0.041665,0.003077,0.996933,0,0.050027,-0.076305,0.008325,0.991744,1,0.005701,0.994338,84,170
85,-0.025148,0.029128,0.001481,0.998521,0,0.034522,-0.094564,0.010134,0.989967,1,0.005808,0.994244,85,172
86,-0.023399,0.033418,0.001664,0.998339,0,0.034522,-0.094564,0.010134,0.989967,1,0.005899,0.994153,86,174
87,-0.023399,0.033418,0.001664,0.998339,0,0.034017,-0.074537,0.006713,0.993332,1,0.004189,0.995835,87,176
88,-0.023144,0.028394,0.001342,0.998660,0,0.046897,-0.061251,0.005951,0.994084,1,0.003646,0.996372,88,178
89,-0.021422,0.023202,0.000997,0.999004,0,0.058705,-0.059317,0.006965,0.993083,1,0.003981,0.996044,89,180
90,-0.010426,0.025281,0.000748,0.999253,0,0.038447,-0.076762,0.007371,0.992683,1,0.004059,0.995968,90,182
91,-0.010426,0.025281,0.000748,0.999253,0,0.047539,-0.076007,0.008037,0.992027,1,0.004392,0.995640,91,184
92,-0.009292,0.025401,0.000732,0.999269,0,0.044303,-0.054086,0.004888,0.995136,1,0.002810,0.997202,92,186
93,-0.009675,0.032664,0.001161,0.998841,0,0.041627,-0.054446,0.004697,0.995325,1,0.002929,0.997083,93,188
94,-0.010077,0.037821,0.001532,0.998470,0,0.041627,-0.054446,0.004697,0.995325,1,0.003115,0.996898,94,190
95,-0.012036,0.034944,0.001366,0.998636,0,0.041627,-0.054446,0.004697,0.995325,1,0.003032,0.996980,95,192
96,-0.012333,0.039177,0.001687,0.998316,0,0.040016,-0.042535,0.003410,0.996601,1,0.002549,0.997459,96,194
97,-0.010227,0.039248,0.001645,0.998358,0,0.040016,-0.042535,0.003410,0.996601,1,0.002528,0.997479,97,196
98,-0.004611,0.026404,0.000718,0.999282,0,0.040807,-0.042593,0.003479,0.996533,1,0.002099,0.997907,98,198
99,-0.003787,0.027548,0.000773,0.999227,0,0.037859,-0.021532,0.001897,0.998107,1,0.001335,0.998667,99,200
100,-0.004103,0.025362,0.000660,0.999340,0,0.033774,-0.018988,0.001501,0.998501,1,0.001081,0.998921,100,202

# Report

### txt

In [6]:
filename = "report_simulated_annealing_01.txt"
with open(filename, "w") as f:
    f.write(report)

### xlsx

In [7]:
filename = "report_simulated_annealing_01.xlsx"
df_resume.to_excel(filename, index=False)