# Import library

In [1]:
# pip install metapy-toolbox or pip install --upgrade metapy-toolbox
from metapy_toolbox import hill_climbing_01
from my_example import my_obj_function

# Setup

In [2]:
# Algorithm setup
setup = {   
            'number of iterations': 100,
            'number of population': 2,
            'number of dimensions': 2,
            'x pop lower limit': [-5, -5],
            'x pop upper limit': [5, 5],
            'none variable': None,
            'objective function': my_obj_function,
            'algorithm parameters': {
                                        'mutation': {
                                                     'cov (%)': 20,
                                                     'pdf': 'gaussian'
                                                    }
                                    },
        }

# Initial guess
init_pop = [[-0.74, 1.25],
            [3.58, -3.33]]
"""
or # random guess
from metapy_toolbox import initial_population_01
init_pop = initial_population_01(setup['number of population'],
                                setup['number of dimensions'],
                                setup['x pop lower limit'],
                                setup['x pop upper limit'])
"""

# Seed
seed = None

# Call function

In [3]:
settings = [setup, init_pop, seed]
df_all_results, df_resume, time_cost, report = hill_climbing_01(settings)

Progress:   0%|          | 0/100 [00:00<?, ?it/s]

Progress: 100%|██████████| 100/100 [00:00<00:00, 749.06it/s]

# Output details

In [4]:
df_all_results.tail(20)

          X_0       X_1        OF       FIT  ITERATION
182 -0.002981  0.002297  0.000014  0.999986         91
183  0.036577 -0.022441  0.001841  0.998162         91
184 -0.002737  0.003238  0.000018  0.999982         92
185  0.024428 -0.022135  0.001087  0.998914         92
186 -0.002814  0.001825  0.000011  0.999989         93
187  0.025946 -0.027876  0.001450  0.998552         93
188 -0.002811  0.001725  0.000011  0.999989         94
189  0.027871 -0.019809  0.001169  0.998832         94
190 -0.003001  0.001815  0.000012  0.999988         95
191  0.019497 -0.027233  0.001122  0.998879         95
192 -0.002510  0.002086  0.000011  0.999989         96
193  0.033231 -0.023951  0.001678  0.998325         96
194 -0.002265  0.001890  0.000009  0.999991         97
195  0.027463 -0.024660  0.001362  0.998640         97
196 -0.002718  0.001833  0.000011  0.999989         98
197  0.031514 -0.024518  0.001594  0.998408         98
198 -0.002538  0.001666  0.000009  0.999991         99
199  0.023190 -0.023727  0.001101  0.998900         99
200 -0.002956  0.001969  0.000013  0.999987        100
201  0.017709 -0.016576  0.000588  0.999412        100

In [5]:
df_resume

,X_0_BEST,X_1_BEST,OF BEST,FIT BET,ID BEST,X_0_WORST,X_1_WORST,OF WORST,FIT WORST,ID WORST,OF AVG,FIT AVG,ITERATION,neof
0,-0.740000,1.250000,2.110100,0.321533,0,3.580000,-3.330000,23.905300,0.040152,1,13.007700,0.180843,0,2
1,-0.740000,1.250000,2.110100,0.321533,0,3.580000,-3.330000,23.905300,0.040152,1,13.007700,0.180843,1,4
2,-0.740000,1.250000,2.110100,0.321533,0,3.580000,-3.330000,23.905300,0.040152,1,13.007700,0.180843,2,6
3,-0.563320,0.974807,1.267577,0.440999,0,3.580000,-3.330000,23.905300,0.040152,1,12.586439,0.240576,3,8
4,-0.510334,0.923568,1.113419,0.473167,0,3.580000,-3.330000,23.905300,0.040152,1,12.509360,0.256659,4,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,-0.002510,0.002086,0.000011,0.999989,0,0.024428,-0.022135,0.001087,0.998914,1,0.000549,0.999452,96,194
97,-0.002265,0.001890,0.000009,0.999991,0,0.024428,-0.022135,0.001087,0.998914,1,0.000548,0.999453,97,196
98,-0.002265,0.001890,0.000009,0.999991,0,0.024428,-0.022135,0.001087,0.998914,1,0.000548,0.999453,98,198
99,-0.002265,0.001890,0.000009,0.999991,0,0.024428,-0.022135,0.001087,0.998914,1,0.000548,0.999453,99,200
100,-0.002265,0.001890,0.000009,0.999991,0,0.017709,-0.016576,0.000588,0.999412,1,0.000299,0.999702,100,202

# Report

### txt

In [6]:
filename = "report_hill_climbing_01.txt"
with open(filename, "w") as f:
    f.write(report)

### xlsx

In [7]:
filename = "report_hill_climbing_01.xlsx"
df_resume.to_excel(filename, index=False)